<!doctype html>
<html>
<head>
    <meta name="robots" content="noindex,nofollow">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>404 Page Not Found</title>
    <style>
body {align-items: center;background-color: #f5f5f5;display: flex;height: 100vh;justify-content: center;margin: 0;}
    .container {text-align: center;}
    .container h1 {font-size: 8rem;letter-spacing: 10px;margin: 0;}
    .container h4 {font-size: 1.25rem;font-weight: 300;}
    </style>
</head>
<body>
    <div class="container">
        <h1>404</h1>
        <h2>Мы не можем найти страницу, которую вы ищете.</h2>
        <h4>Страница, которую вы запросили, не найдена в базе данных.<br> Скорее всего вы попали на битую ссылку или опечатались при вводе URL</h4>
        <p class="box_in"><a href="/">Перейти на главную страницу</a></p>
        <p>Generated by SkinsDle. © 2022</p>
    </div>
</body>
</html>
